version: "3.9"

services:
  db:
    image: postgres:16
    container_name: assessify-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - assessify-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Assessify.Backend
      dockerfile: Dockerfile
    container_name: assessify-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: docker
      # JWT_SECRET:
    ports:
      - "4100:4100"
    networks:
      - assessify-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: assessify-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - assessify-net

networks:
  assessify-net: {}

volumes:
  pgdata: {}
